server:
  port: 9000
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    #虚拟host 可以不设置,使用server默认host
    virtual-host: /
    #消息确认配置项
    #确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated
    # springboot版本低用下面这个，版本高用上面这个
#    publisher-confirms: true
    #确认消息已发送到队列(Queue)
    publisher-returns: true
